---
- name: Install/Upgrade Engineering Casks
  homebrew_cask:
    name:
      - pop
      - session-manager-plugin
    state: latest

- name: Source tfswitch ğŸ“¦
  homebrew_tap:
    name: warrensbox/tap
    url: git@github.com:warrensbox/tap.git
    state: present

- name: Install/Upgrade tfswitch ğŸ“¦
  homebrew:
    name: tfswitch
    state: latest
  # TODO: switch to tfenv

- name: Install/Upgrade Cloud Software â˜ï¸
  homebrew:
    name:
      - awscli
    state: latest
