---
- name: Install Mac App Store ğŸ›ï¸ CLI
  community.general.homebrew:
    name:
      - mas
    state: present

- name: Install Wireguard ğŸŒ from App Store (GameChanger VPN)
  community.general.mas:
    id: 1451685025 # `mas search Wireguard`
    state: present
