[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold green)"

[localip]
disabled = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"
unknown_symbol = "â“ "
empty_symbol = "â— "

[cmake]
symbol = "ğŸ› ï¸ "

[conda]
symbol = "ğŸ "

[container]
symbol = "ğŸ³"

[hg_branch]
symbol = "ğŸŒ± "

[fossil_branch]
symbol = "ğŸŒ± "

[git_branch]
symbol = "ğŸŒ± "

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ¢"
stashed = "ğŸ“¦"
staged = '[++\($count\)](green)'

[golang]
symbol = "ğŸ¦¦ "

[nodejs]
symbol = "âš™ï¸ "

[purescript]
symbol = "ğŸ”· "

[terraform]
symbol = "ğŸ—ï¸ "

[vagrant]
symbol = "ğŸ“¦ "
